name: aaronbelford
favicon: null
layout_spectrum: 0.76156
typography_spectrum: 0.75289
title: aaronbelford
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-68638679-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8f8'
    - '#000000'
    - '#fa7f46'
    - '#a0a19c'
    - '#414244'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    url: null
    item: 0eae9a22-da9a-416b-8fb1-eeafc758f9ac
