name: aaronbelford
favicon: null
layout_spectrum: 0.52457
typography_spectrum: 0.61685
title: aaronbelford
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-68638679-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff7a07'
    - '#595959'
    - '#ebebeb'
    - '#000000'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    url: null
    item: 0eae9a22-da9a-416b-8fb1-eeafc758f9ac
