name: aaronbelford
favicon: null
layout_spectrum: 0.8
title: aaronbelford
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-68638679-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
