typography_spectrum: 0.61685
color:
  brandColors:
    - '#ff7a07'
    - '#595959'
    - '#ebebeb'
    - '#000000'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.52457
analytics:
  google: UA-68638679-1
  facebook: null
  twitter: null
name: aaronbelford
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: aaronbelford
description: Shooting Crazy Action In The Middle Of Nowhere
purpose: []
