name: aaronbelford
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6310419
title: aaronbelford
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-68638679-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#E95F01'
    - '#FFA365'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose:
  - name: awareness
    url: null
    item: 'null'
